project_id = "yduosziameskzofrcodg"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.generate-chart]
verify_jwt = true

[functions.upload-file]
verify_jwt = true

[functions.conversational-chat]
verify_jwt = false

[functions.generate-multiple-charts]
verify_jwt = false

[functions.generate-policies]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false

[auth]
enabled = true
email_double_confirm_changes = true
enable_signup = true